import json
import sys
import unittest
from pathlib import Path
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'scripts'))
import build  # noqa: E402


class ParsingTests(unittest.TestCase):
    def test_population_chooses_latest_nonempty(self):
        result = build.parse_population([
            {'page': 1},
            [{'date': '2023', 'value': 100}, {'date': '2025', 'value': 1234},
             {'date': '2026', 'value': None}, {'date': '2024', 'value': 345}],
        ])
        self.assertEqual(result['year'], 2025)
        self.assertEqual(result['value'], 1234)

    def test_population_rejects_invalid_data(self):
        with self.assertRaises(ValueError):
            build.parse_population([{'page': 1}, [{'date': '2020', 'value': None}]])

    def test_wikidata_reads_inception_and_country_code(self):
        sample = {'entities': {'Q805': {'claims': {
            'P297': [{'mainsnak': {'datavalue': {'value': 'YE'}}}],
            'P571': [{'mainsnak': {'datavalue': {'value': {'time': '+1990-05-22T00:00:00Z'}}}}],
        }}}}
        result = build.parse_wikidata(sample)
        self.assertEqual(result['inception_date'], '22 May 1990')
        self.assertEqual(result['country_code'], 'YE')

    def test_offline_content_has_six_sections_and_citations(self):
        # The checked-in seed is generated by exactly the same combiner.
        editorial = build.read_json(build.ROOT / 'sources' / 'editorial.json')
        archive = build.read_json(build.ROOT / 'sources' / 'factbook_archive.json')
        data = build.compose(editorial, archive,
            {'value':41773878,'year':2025},
            {'country_code':'YE','inception_date':'22 May 1990'},
            {}, 'starter', [], '2026-10-07T00:00:00Z')
        self.assertEqual(len(data['sections']), 6)
        self.assertIn('41,773,878', str(data['sections']))
        for section in data['sections']:
            self.assertTrue(all(x['sources'] for x in section['paragraphs']))

    def test_zero_network_checks_do_not_overwrite(self):
        class Blocked(Exception):
            pass
        def no_fetch(*args):
            raise OSError('offline')
        with self.assertRaises(RuntimeError):
            build.build(offline=False, fetcher=no_fetch, wiki_fetcher=no_fetch)


if __name__ == '__main__':
    unittest.main()

class IntegrationTests(unittest.TestCase):
    def test_mocked_successful_refresh(self):
        import tempfile
        from datetime import datetime, timezone
        def simulated_fetch(url):
            if 'wikidata.org' in url:
                return {'entities': {'Q805': {'claims': {
                    'P297': [{'mainsnak': {'datavalue': {'value': 'YE'}}}],
                    'P571': [{'mainsnak': {'datavalue': {'value': {'time': '+1990-05-22T00:00:00Z'}}}}],
                }}}}
            return [{}, [{'date': '2026', 'value': 42000000}, {'date': '2025', 'value': 41000000}]]
        with tempfile.TemporaryDirectory() as folder:
            output = Path(folder) / 'sections.json'
            with patch.object(build, 'OUTPUT', output):
                data = build.build(offline=False,
                    fetcher=simulated_fetch,
                    wiki_fetcher=lambda article: 'Yemen is on the Arabian Peninsula, with mountains and desert, Saba, Arabic, and conflict.' * 2,
                    now=datetime(2026, 10, 7, tzinfo=timezone.utc))
                self.assertEqual(data['build_mode'], 'refreshed')
                self.assertIn('42,000,000', str(data['sections']))
                self.assertTrue(output.exists())
                self.assertEqual(json.loads(output.read_text())['population']['year'], 2026)
